version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bus_booking-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    networks:
      - bus_booking-network



  redis:
    image: redis:7
    container_name: bus_booking-redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - bus_booking-network

  auth-db:
    image: mysql:8.0
    container_name: bus_booking-auth-db

    environment:
      MYSQL_DATABASE: bus_booking_auth_service
      MYSQL_USER: bus_booking_auth_user
      MYSQL_PASSWORD: bus_booking_auth_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3306:3306"

    volumes:
      - auth-db-data:/var/lib/mysql

    networks:
      - bus_booking-network


  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth-service

    container_name: bus_booking-auth-service

    env_file:
      - ./services/auth-service/.env

    ports:
      - "4001:4001"

    depends_on:
      - auth-db
      - rabbitmq
      - redis

    networks:
      - bus_booking-network



volumes:
  rabbitmq-data:
  redis-data:
  auth-db-data:

networks:
  bus_booking-network:
    driver: bridge